traffic_sign_detection
osechkina-masha/adas_spbu pull request #5
Opened 2022-12-15 16:16 UTC by rongirl

2023-01-02 15:45 UTC, yurii-litvinov requested changes

2023-01-02 15:45 UTC, yurii-litvinov commented on traffic_signs_detection/traffic_signs_detection/detectorPolygons.cpp
> +std::vector<cv::Vec3f> detectorPolygons::detectCircle(cv::Mat frame)
Объекты размером больше 8 байт в C++ надо по константной ссылке передавать:
```suggestion
std::vector<cv::Vec3f> detectorPolygons::detectCircle(const cv::Mat &frame)
```
Иначе они копируются при каждом вызове, это не очень с точки зрения скорости работы.

2023-01-02 15:45 UTC, yurii-litvinov commented on traffic_signs_detection/traffic_signs_detection/detectorPolygons.h
> +class detectorPolygons
Именовать классы со строчной не принято

2023-01-02 15:45 UTC, yurii-litvinov commented on traffic_signs_detection/traffic_signs_detection/detectorPolygons.h
> +    static std::vector<cv::Vec3f> detectCircle(cv::Mat frame);
А если фронт будет на Qt, то там и методы с заглавной именуются

2023-01-02 15:45 UTC, yurii-litvinov commented on traffic_signs_detection/traffic_signs_detection/detectorPolygons.h
> +    // Detects circles in an image
Погуглите про Doxygen

2023-01-02 15:45 UTC, yurii-litvinov commented on traffic_signs_detection/traffic_signs_detection/imageSegmentation.cpp
> +    cv::medianBlur(originalImage, originalImage, 1);
Пробелы и табуляции перепутаны, это совсем не очень

2023-01-02 15:45 UTC, yurii-litvinov commented on traffic_signs_detection/traffic_signs_detection/main.h
> +﻿#pragma once
Это вообще не нужно, у main не должно быть хедера :)

2023-01-18 20:47 UTC, osechkina-masha commented
есть ощущение, что medianBlur очень много. Нужно перепроверить везде ли он нужен. Возможно, стоить заблерить всю картинку в начале (=убрать шумы) и после этого больше не применять medianBlur

2023-01-18 20:51 UTC, osechkina-masha commented on traffic_signs_detection/traffic_signs_detection/detectorPolygons.cpp
> +    medianBlur(grayImage, grayImage, 5);
5 - не великоват ли порог?

2023-01-18 20:51 UTC, osechkina-masha commented on traffic_signs_detection/traffic_signs_detection/detectorPolygons.cpp
> +        grayImage.rows / 16,
минимальное расстояние великовато

2023-01-18 20:51 UTC, osechkina-masha commented on traffic_signs_detection/traffic_signs_detection/detectorPolygons.cpp
> +        100, 30, 10, 40);
параметры лучше вынести в константы

2023-01-18 20:51 UTC, osechkina-masha commented on traffic_signs_detection/traffic_signs_detection/imageSegmentation.cpp
> +    cv::medianBlur(originalImage, originalImage, 1);
выглядит как лишняя строчка

2023-01-18 20:51 UTC, osechkina-masha commented on traffic_signs_detection/traffic_signs_detection/imageSegmentation.cpp
> +}
выглядит как копипаст highlightYellow. Нужно сделать один метод и передавать параметры inRange через параметры метода.

2023-01-18 20:51 UTC, osechkina-masha commented on traffic_signs_detection/traffic_signs_detection/imageSegmentation.cpp
> +	return newImage;
еще копипаст

2023-01-18 20:51 UTC, osechkina-masha commented on traffic_signs_detection/traffic_signs_detection/imageSegmentation.cpp
> +	redImage = redImage1 + redImage2;
почему красный такой особенный? почему в отличие от остальных методов необходимо 2 inRange?

2023-01-18 20:51 UTC, osechkina-masha commented on traffic_signs_detection/traffic_signs_detection/main.cpp
> +        cv::imshow("yellow", yellow);
метод - четырехкратная комипаста. Нужен один метод, который будет вызываться 4 раза с разными параметрами

2023-03-07 08:07 UTC, yurii-litvinov requested changes

2023-03-07 08:07 UTC, yurii-litvinov commented on traffic_signs_detection/traffic_signs_detection/detectorPolygons.cpp
> +    cv::Mat templateTriangle = cv::imread("C:/Users/Acer/source/repos/adas_spbu/traffic_signs_detection/traffic_signs_detection/t.png", cv::IMREAD_GRAYSCALE);
Абсолютные пути нельзя, даже в прототипе :)

2023-03-13 14:40 UTC, rongirl commented on traffic_signs_detection/traffic_signs_detection/imageSegmentation.cpp
> +	redImage = redImage1 + redImage2;
Если использовать один inRange, то обнаружение красных объектов будет более не точным. Я конвертирую изображение в hsv, а для красного цвета hue имеет два диапазона.

2023-03-20 18:45 UTC, osechkina-masha commented
Ошибка при сборке
In file included from /home/mariya/adas_spbu/traffic_signs_detection/traffic_signs_detection/main.cpp:3:
/home/mariya/adas_spbu/traffic_signs_detection/traffic_signs_detection/trafficSign.h:13:17: error: extra qualification ‘TrafficSign::’ on member ‘showTrafficSigns’ [-fpermissive]
   13 |     static void TrafficSign::showTrafficSigns(const cv::Mat& colorImage, const cv::Mat& frame);

2023-03-20 19:32 UTC, merged